name: Google Cloud CI/CD Pipeline

on:
  push:
    branches:
      - dev/cicd
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend-workflow.yaml'
      - README.md
      - config/envoy.yaml

jobs:
  job1:
    name: build-test-deploy
    runs-on: ubuntu-24.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          docker build -t us-central1-docker.pkg.dev/go-slowmo/go-slowmo/slowmo-server:latest --target slowmo-server .
          docker build -t us-central1-docker.pkg.dev/go-slowmo/go-slowmo/exec-server:latest --target exec-server .

      - name: Google Cloud authentication
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 390.0.0'
      
      - name: Deploy Cloud Run service
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: go-slowmo
          image: us-central1-docker.pkg.dev/go-slowmo/go-slowmo/slowmo-server:latest
